language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build
  - bundle exec rake test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $repo_access_token
  keep-history: true
  on:
    branch: master
