title:        marii¨
baseurl:      ''
url:          ''

favicon:      '/assets/favicon.ico'
date_format:  "%Y"
permalink:    notes/:slug
post_title:   Notes
post_date:    Time Period
post_cat:     Tags
prev-next:    true
markdown:     kramdown
theme:        marii-theme
source:       src

collections:
  projects:
    output: true
    permalink: projects/:slug

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
