# Site Info
title:              "marii"
description:        "marii nyrop — dh developer @columbia. planetary computation, cybernetic history, soviet sci-fi, fiber art."

# Author Info
author_name:        "marii" # Your name here
twitter_username:   mariinyrop # Your Twitter username here
github_username:    mnyrop # Your GitHub username here

# Site Settings
url:                ""
permalink:          /notes/:title # Post permalink

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile*" ]

collections:
  projects:
    output: true

footer_links:
  - icon: fa fa-lg fa-twitter
    link: https://twitter.com/mariinyrop
  - icon: fa fa-lg fa-code-fork
    link: https://github.com/mnyrop
  - icon: fa fa-lg fa-stack-overflow
    link: https://stackoverflow.com/users/8227741/marii
  - icon: fa fa-lg fa-jsfiddle
    link: https://jsfiddle.net/user/marii_/fiddles/
  - icon: fa fa-lg fa-diamond
    link: https://rubygems.org/profiles/marii
