# site
title: marii¨
baseurl: ""
url: ""
favicon: "/assets/snake.png"
g_analytics: '' #UA-12345678-1

# bio
header: marii¨
desc: >
  libraries ☞ minimal computing ☞ soviet sci-fi ☞ fiber art.

date_format: "%Y"
permalink: notes/:slug

post_title: Notes
post_date: Time Period
post_cat: Tags

collections:
  projects:
    output: true
    permalink: projects/:slug

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
