# Site Info
title:              "marii nø"
description:        "dh developer @columbia; planetary computation, cybernetic history, soviet sci-fi, fiber art;"

# Author Info
author_name:        "marii" # Your name here
twitter_username:   mariinyrop # Your Twitter username here
github_username:    mnyrop # Your GitHub username here

# Site Settings
url:                ""
permalink:          /notes/:title # Post permalink

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile*" ]

collections:
  projects:
    output: true
