# site
title: Louie
baseurl: "/louie"
url: "http://lily.work"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Louie
desc: >
  A Jekyll theme (that looks awesome). Louie is free, lightweight,
  and customizable as a blog, archive, or portfolio.

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock